FROM node:20-alpine AS builder
WORKDIR /app
RUN apk add --no-cache python3 make g++ gcc
COPY package*.json ./
RUN npm ci --omit=dev


FROM node:20-alpine
WORKDIR /app 
RUN apk add --no-cache dumb-init

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./ 
COPY . . 


USER node 

EXPOSE 3000

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD ["node","server.js"]
