##
# Cấu hình Nginx cho máy chủ Backend (192.168.6.126)
# Nhận các yêu cầu từ Private ALB gửi tới cổng 80 và chuyển tiếp nội bộ vào Node.js (cổng 3000)
##

server {
    listen 80;
    server_name _;

    client_max_body_size 4m;

    # Chuyển tiếp các request gọi API thông thường vào Node.js cổng 3000
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
    }

    # Chuyển tiếp và nâng cấp kết nối WebSocket cho Socket.io vào Node.js cổng 3000
    location /socket.io/ {
        proxy_pass http://127.0.0.1:3000; # Chuyển tiếp nội bộ vào Node.js port 3000
        proxy_http_version 1.1;
        
        # Thiết lập các Header nâng cấp giao thức WebSocket
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Thiết lập thời gian timeout dài để tránh ngắt kết nối WebSocket đột ngột
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
